### ISSUE TITLE
Runtime Error 216 MessageWindows shown in cef_shutdown()

### ISSUE THREAD

**Issue by SDiestelmann** [salvadordf/CEF4Delphi#328] opened 2020-12-03 16:47 UTC
Hi I get runtime error in cef_shutdown in my App called from DestroyGloblCEFApp.
My App is similar to MDIBrowser.pas (which does not throw 216)
What can i do to find the Source for this Problem ? 

Very anoying is the MessageWindows shown at the End of the App.

**Comment by salvadordf** [comment] 2020-12-03 17:16
That error is usually caused by an incomplete destruction implementation. CEF needs to close all the web browsers following certain steps before closing the main application form.

Make sure the child forms follow these steps : 
https://github.com/salvadordf/CEF4Delphi/blob/80b1140db6c2db7c75b1b0043c852890eb94f33c/demos/Delphi_VCL/MDIBrowser/uChildForm.pas#L110

And the main form needs to follow these steps : 
https://github.com/salvadordf/CEF4Delphi/blob/80b1140db6c2db7c75b1b0043c852890eb94f33c/demos/Delphi_VCL/MDIBrowser/uMainForm.pas#L106

Notice that the main form overrides TForm.CloseQuery and receives a CEFBROWSER_CHILDDESTROYED message for every destroyed child form.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Closed by salvadordf** 2020-12-03 17:16 UTC
