### ISSUE TITLE
External exception 80000003

### ISSUE THREAD

**Issue by jdredd87** [salvadordf/CEF4Delphi#442] opened 2022-12-04 01:54 UTC
Been getting this on a number of systems all of a sudden.  Systems where the files been the same for a few weeks and running great up until last few days.

Not sure windows update? or something causing issues?

"Faulting application name: eBayOAuthClientTool.exe, version: 1.0.0.0, time stamp: 0x6340327d
Faulting module name: libcef.dll, version: 106.0.26.0, time stamp: 0x63363283
Exception code: 0x80000003
Fault offset: 0x030ffe12
Faulting process id: 0x0x5780
Faulting application start time: 0x0x1D906FAAEC0540B
Faulting application path: C:\ebayfix\eBayOAuthClientTool.exe
Faulting module path: C:\ebayfix\libcef.dll
Report Id: 1737be20-03db-46df-9fce-5f76fbd21c5b
Faulting package full name: 
Faulting package-relative application ID: "

I don't have the issue ( go figure ) but I have a few other systems that do.

Nothing program/cef files/ect changed in weeks.

What is odd... nothing is going on with CEF.  Its idle.  Only used for one function that the user must do to trigger bringing up
the browser object.

Only the CEF startup code is being at the time of erroring out.

**Comment by salvadordf** [comment] 2022-12-04 08:44
Add these two code lines before the GlobalCEFApp.StarMainProcess call in the DPR : 
`  GlobalCEFApp.LogFile             := 'debug.log';`
`  GlobalCEFApp.LogSeverity         := LOGSEVERITY_VERBOSE;`

Those lines will enable the debug log in the same directory as your application. That debug log will grow a lot so add the means to enable or disable it only when it's needed.

Please, provide more details : 
- What version of CEF4Delphi is your application using?
- What's the operating system version?
- Were the users trying to run some other application when they got that error?
- Were the users trying to suspend, hibernate or wake up the system?
- Is your application using a different EXE for the Chromium subprocesses?

It would be extremely helpful if you could provide a simple demo to reproduce that error in my computer.

**Comment by salvadordf** [comment] 2023-06-25 09:43
Closing due to lack of information.

**Closed by salvadordf** 2023-06-25 09:43 UTC
