### ISSUE TITLE
ActiveControl for CEF

### ISSUE THREAD

**Issue by mcdurdin** [salvadordf/CEF4Delphi#129] opened 2018-08-28 07:10 UTC
We have found that CEF4Delphi does not update the parent form's (or `TScreen`'s) `ActiveControl` property when focused. This means that TAction and other interactions think the wrong control has focus when they are updated.

As a workaround we did the following (`cefwp` is a `TCEFWindowParent` control):

```delphi
procedure TframeCEFHost.cefWidgetCompMsg(var aMessage: TMessage; var aHandled: Boolean);
begin
  if aMessage.Msg = WM_SETFOCUS then
    if cefwp.Visible and cefwp.CanFocus then
      GetParentForm(cefwp).ActiveControl := cefwp;
end;
```

However, something of this nature would be better placed in the component itself -- and there may be a cleaner way of implementing this with Chromium's existing focus events (although `OnGotFocus` and related events did not fire at the appropriate time)

**Comment by salvadordf** [comment] 2018-08-28 09:36
I'm not sure how to proceed with this issue. 

TForm.ActiveControl is a TWinControl property. It's supposed to have the Delphi TWinControl that has the focus or the TWinControl that will get the focus when the Form gets the focus : 
http://docwiki.embarcadero.com/Libraries/Tokyo/en/Vcl.Forms.TForm.ActiveControl

The problem is that CEF3 creates a couple of child "windows" (using the Windows API terminology), they are not TWinControl and one of them has the focus.

Read this forum post for more info about those windows : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=530#p2347

**Comment by mcdurdin** [comment] 2018-08-28 09:50
From what I understand, when a non-Delphi window is a child of a TWinControl, the TForm.ActiveControl should refer to that TWinControl whenever the non-Delphi window has focus. That's certainly how other components such as TWebBrowser work in practice. I'm not yet familiar enough with the CEF3 internals to know the best way to make that happen, but the snippet I provided worked in my test scenarios.

**Comment by salvadordf** [comment] 2018-08-28 13:35
The parent of those windows is TCEFWindowParent.

...and that is another problem because TCEFWindowParent set the focus to the child window automatically when it receives WM_FOCUS. This would create an infinite loop if the browser sets the focus to TCEFWindowParent.

The CEF3 project maintainer knows the CEF3 and Chromium source code a lot better than me and I always try to replicate what he does in the official CEF3 client application, called '_cefclient_'. 

In this case, cefclient also sets the focus to the browser automatically when it receives WM_FOCUS.

The way VCL uses the ActiveControl property is in conflict with the way cefclient works. 

Right now I'm busy but I'll take a look at this as soon as I can.

**Comment by salvadordf** [comment] 2018-09-16 08:55
I made some more tests with the CEF4Delphi version I just uploaded and the TForm.ActiveControl and screen.ActiveControl seem to keep the TCEFWindowParent value even when the browser has the focus. 

I had to set TCEFWindowParent.TabStop := True in the demo in order to keep the right ActiveControl value.

I also added a new component called TCEFLinkedWindowParent that uses the linked TChromium to set the focus. TCEFLinkedWindowParent is almost the same as TCEFWindowParent but it has a "Chromium" property where you select the TChromium component that will be used internally to set the focus.

You can use TCEFWindowParent or TCEFLinkedWindowParent. Both of them will keep the right ActiveControl value as long as their "TabStop" property is true.

**Comment by salvadordf** [comment] 2018-11-30 07:40
Closing. This issue was fixed in September.

**Closed by salvadordf** 2018-11-30 07:40 UTC
