### ISSUE TITLE
When closing application remains open in processes

### ISSUE THREAD

**Issue by edsonalvesan** [salvadordf/CEF4Delphi#272] opened 2020-04-02 18:53 UTC
When the application is closed, it remains open in Windows processes.

**Comment by salvadordf** [comment] 2020-04-02 19:08
You need to follow the destruction steps described in the code comments of the demo you used as a template for your application.

If you implement those steps and you still see that problem please, provide a complete example to reproduce the issue.

**Comment by t0pfHub** [comment] 2020-04-22 06:50
I have the same Problem with the SimpleBrowser Demo. 
Compiles and runs but when closing there seems to be an error. 
In debugging the stack is on \bin\libcef.dll and the error is:
system exception (code 0x0000001d) at 0x12164384
got the binaries here: http://opensource.spotify.com/cefbuilds/cef_binary_81.2.17%2Bgb382c62%2Bchromium-81.0.4044.113_windows32.tar.bz2
Working with Delphi 10.3 on Windows10

**Comment by salvadordf** [comment] 2020-04-22 17:40
Are you using the CEF binaries found in the "Release" folder or the "Debug" folder?

**Comment by t0pfHub** [comment] 2020-04-23 08:30
When debugging I use the Debug-binaries and get the error.
When compiling in release with Release-binaries I can close the app and nothing stays in memory.
However, the TabBrowser Demo is working in debug with the same Debug-binaries that seem to cause the error in SimpleBrowser.

**Comment by salvadordf** [comment] 2020-04-23 08:58
The debug binaries have many more checks than the release binaries that cause problems like this one. 

You should use them only when you detected an issue in the CEF libraries and you need to get the trace. 

For any other situation, including normal Delphi development, you should use the "release" binaries.

**Closed by salvadordf** 2020-04-23 08:58 UTC
