### ISSUE TITLE
Builds after 98.2.1 work incorect with domtoimage js

### ISSUE THREAD

**Issue by kapindows** [salvadordf/CEF4Delphi#410] opened 2022-03-10 18:41 UTC
Unfortunately, I do not have a code example from the front end but for the last 3 years all was ok and this LIB (https://github.com/tsayen/dom-to-image) does its job good. Like that
![image](https://user-images.githubusercontent.com/35061331/157732040-ddce9611-79d3-45e3-8405-89cb86d8e7fc.png)
but with two latest build series 99+ give results like that =((
![image](https://user-images.githubusercontent.com/35061331/157732456-a4dbe3a7-3387-4f02-b461-59dce6e90ad1.png)

**Comment by salvadordf** [comment] 2022-03-10 20:12
Hi,

Is that library using the PDF viewer? If so, perhaps this issue is caused by this :
https://bitbucket.org/chromiumembedded/cef/issues/3047/add-support-for-new-non-ppapi-pdf-viewer

In any case, this looks like an upstream issue or a consequence of a deprecated API in that library, which hasn't been updated for several years.

Could you test that library with the same version of Chrome?
If that works fine then please, test it with the official CEF sample application.
https://cef-builds.spotifycdn.com/cef_binary_99.2.10%2Bgfecf7ca%2Bchromium-99.0.4844.51_windows32_client.tar.bz2

**Comment by salvadordf** [comment] 2022-03-10 20:16
Perhaps what you are experimenting is related to this issue in that library : 
https://github.com/tsayen/dom-to-image/issues/410

**Comment by kapindows** [comment] 2022-03-12 07:12
thx for your reply. I am trying to test with a normal Chrome browser currently. But it's not so easy in my case. And yes latest 99.2.10 I try before opening this issue. Let's hope the author of LIB is still alive and activly support his code...

**Comment by salvadordf** [comment] 2022-03-12 09:12
Closing. This issue was caused by an outdated library.

**Closed by salvadordf** 2022-03-12 09:12 UTC
