### ISSUE TITLE
Cannot type characters with alt + altcode in OSR mode

### ISSUE THREAD

**Issue by mterrisse** [salvadordf/CEF4Delphi#378] opened 2021-09-01 09:34 UTC
[CEF 92.0.27, Windows 10 21H1]

Hello,

On Windows we can type characters that are not directly accessible from the keyboard with alt key plus a code, for exemple:
alt + 128 (Ç), alt + 164 (ñ), alt + 165 (Ñ), alt + 0201 (É)

It works fine with demos\Delphi_VCL\MiniBrowser\MiniBrowser.dproj but not with demos\Delphi_VCL\SimpleOSRBrowser\SimpleOSRBrowser.dproj.

I tried to fix it myself but couldn't make it work.
Could you please suggest me a fix for this?

Regards,

Michel Terrissse

**Comment by mterrisse** [comment] 2021-09-01 10:08
I forgot to specify that it works fine with cefclient.exe --off-screen-rendering-enabled

Regards,

Michel Terrisse

**Comment by salvadordf** [comment] 2021-09-01 13:53
I'll compare the keyboard handling code in cefclient with SimpleOSRBrowser's code as soon as I have time. 
Thanks for reporting this issue!

**Comment by salvadordf** [comment] 2021-09-05 08:50
This issue was fixed in the latest update. Please download CEF4Delphi again.

**Closed by salvadordf** 2021-09-05 08:50 UTC
Labels: bug

**Comment by mterrisse** [comment] 2021-09-05 21:19
I wouldn't have thought it could come from those Handled := True.
Thank you very much for the fix.

Regards,

Michel Terrisse

**Comment by mterrisse** [comment] 2021-09-17 07:47
Hello,

We discovered a bad side effect of this fix : Handled is not set to true whereas the key events are handled. So if there is a button with an accelerator on the same form, when you type the letter of the accelerator in chromium, the onClick event on the button is triggered.
I fixed it this way in our products in the equivalent of TOSRExternalPumpBrowserFrm.AppEventsMessage
  WM_KEYUP, I added Handled := (Msg.wParam <> VK_MENU);
  WM_CHAR, I restaured Handled := True;
And for security at the beginning of AppEventsMessage I added
  if Handled then exit;
because there can be other TApplicationEvents in the applications.

Regards,

Michel Terrisse

**Comment by mterrisse** [comment] 2021-09-17 10:23
Here is a patch for uOSRExternalPumpBrowser.pas, it is probably easier to understand.

[Handled.zip](https://github.com/salvadordf/CEF4Delphi/files/7184865/Handled.zip)

Regards,

Michel Terrisse

**Comment by salvadordf** [comment] 2021-09-17 15:47
I tried to replicate this issue with an accelerator in the "Go" button of the OSRExternalPumpBrowser demo and I couldn't reproduce it on Delphi 11.

**Comment by mterrisse** [comment] 2021-09-20 15:19
Hello,
I an reproduce it even with Delphi 11, CEF4Delphi source code updated today (fe3d171c5b9ce0c1c4a8a7ea4aff8ab8dc4a7a1e).
In uOSRExternalPumpBrowser.dfm just change 'Go' to 'Go&Z' and run the project.
In the Google page, start typing abc..., when you type z the page is reloaded.

Regards,

Michel Terrisse

**Comment by salvadordf** [comment] 2021-09-27 10:05
I added the keyboard handling modification you requested in the last update.
