### ISSUE TITLE
With latest version SubProcess is no longer working

### ISSUE THREAD

**Issue by nalilord** [salvadordf/CEF4Delphi#167] opened 2019-02-28 11:40 UTC
I recently updated to the latest version and now the SubProcess feature is now longer working.

Even the demo application (\demos\SubProcess) does not load the browser window, only a blinking wait cursor.

Tested in 32bit with RAD Studio 10.1 under Windows 10 (1809).

![simplebrowser_2019-02-28_12-38-12](https://user-images.githubusercontent.com/3942265/53563887-b6676880-3b55-11e9-82c6-5d77d02006e7.png)

**Comment by salvadordf** [comment] 2019-02-28 13:37
I just tested the SubProcess demo in Windows 7 and Windows 10, and It works correctly.

Please, check that you compiled the _SimpleBrowser_ and _SubProcess_ projects found inside the 
_\demos\SubProcess_ folder and the executables are located in the _BIN_ folder. 

Also check that the contents of the CEF binaries are copied to the _BIN_ folder. The final layout looks like this for the MiniBrowser demo : 
https://www.briskbard.com/images/ceflayout.png

**Comment by nalilord** [comment] 2019-02-28 16:54
As I stated it stopped working after I updated to the latest git version, before everything was fine, my application does not load the browser so does (or not) the sample.

Looks good to me:
![explorer_2019-02-28_17-39-10](https://user-images.githubusercontent.com/3942265/53582434-c4ca7a00-3b7f-11e9-9dfd-53efff06f78a.png)

I used the cef binaries from: http://opensource.spotify.com/cefbuilds/cef_binary_3.3626.1891.g52be333_windows32.tar.bz2

[SimpleBrowser.zip](https://github.com/salvadordf/CEF4Delphi/files/2915988/SimpleBrowser.zip) (My compiled binaries)
[Recording.zip](https://github.com/salvadordf/CEF4Delphi/files/2915994/Recording.zip) (Screen recording)

I also copied the bin folder to my Windows Server 2012 R2 machine to test it there, same result.

**Comment by salvadordf** [comment] 2019-03-01 18:42
I tested your SimpleBrowser and I had the same problem. This could be some unexpected Delphi issue or some problem with other installed components. 

I only have a Delphi Community Edition 10.3 license and I can't test RAD Studio 10.1.

I'll try to figure out what could be happening but please, test this : 
https://www.briskbard.com/SimpleBrowser.zip

That zip has the SubProcess, MiniBrowser and TabBrowser demos that I just built and they work fine in my Windows 7 and Windows 10 PCs.

**Comment by nalilord** [comment] 2019-03-05 14:16
I tested you compiles and they are working fine, that is strange. Does the new 10.3 have other compiler defaults like byte align or default enum sizes that may not conflict or needed to work with the latest C code of cef? Hmm...

Maybe it's just a project configuration thing in 10.1. I will check this!

**Comment by salvadordf** [comment] 2019-07-18 09:57
I can't reproduce this issue. Closing.

**Closed by salvadordf** 2019-07-18 09:57 UTC
Labels: bug
